### ISSUE TITLE
subset_data error with calc_rate.bg

### ISSUE THREAD

**Issue by nicholascarey** [januarharianto/respR#100]
All output rates are NA

``` 
subset_data(urchins.rd[,c(1,18:19)], from = 3, to = 13, by = "time") %>%
  calc_rate.bg(plot = FALSE)
```

Works
``` 
subset_data(urchins.rd[,c(1,18:19)], from = 3, to = 13, by = "time") %>%
  as.data.frame() %>%
  calc_rate.bg(plot = FALSE)
``` 

Therefore probably something to do with output being a `data.table`. 

Should take opportunity to revise tests to check output works with subsequent functions.

**Comment by januarharianto** [comment]
Hmm this has happened before in `calc.rate()` as well, happens whenever `data.table` changes its underlying code. Seems like an easy fix - convert back using `as.data.frame()` after using `data.table()`?

**Comment by nicholascarey** [comment]
Hmm. Yes, error was with `calc_rate.bg` not working correctly with `data.tables` rather than `subset_data` outputting them.

However, I'm now unable to reproduce, even using example above, which was from working in `feature/adjust_rate`  branch. Works fine in `develop` after i merged. Updated packages earlier, so possibly i updated `data.table`, but version in my lib came out in Dec 2019, so unlikely. So not sure what's going on...

Anyway, added some extra `calc_rate.bg` tests so if it happens again they should be caught.
