### ISSUE TITLE
v1.x  -  persistent link with working dependencies included

### ISSUE THREAD

**Issue by nicholascarey** [januarharianto/respR#110]
So when we release v2 there are enough small, unavoidable changes to the code that v1.x code may fail to work or output different results. Therefore for users who are preparing submissions, or have already done so, we should have a persistent link to v1.x that they can include in their code so it will remain reproducible in the future. The 'Releases' links can work for this, however, they don't (AFAIK) include dependencies, which may change in the future in some way that breaks `respR` code. 

There must be some standard way of doing this, but i am struggling to find any online. Maybe include them within a package archive file? Or specify known older working versions of the dependencies so that these are installed (from a CRAN archive i guess) along with `respR`?

Is Packrat for this? 
https://rstudio.github.io/packrat/
Reply here seems to suggest so
https://stackoverflow.com/questions/39901902/r-how-to-download-the-zip-binaries-and-all-the-dependencies-of-a-list-of-packag

This might help too
https://support.rstudio.com/hc/en-us/articles/219949047-Installing-older-versions-of-packages

**Comment by nicholascarey** [comment]
https://rstudio.github.io/renv/articles/renv.html

**Comment by januarharianto** [comment]
We can also archive a version of the package using a doi identifier that preserves versioninfo, but I think `renv` is probably the simplest implementation.

...lol @ my super late response

**Comment by nicholascarey** [comment]
no worries,  using this as a reminder to myself as much as asking you :)
