### ISSUE TITLE
Error in plot.window(...) : need finite 'xlim' values In addition: Warning messages:

### ISSUE THREAD

**Issue by Skvanto** [januarharianto/respR#111]
Hi,

I am getting this error:

Error in plot.window(...) : need finite 'xlim' values
In addition: Warning messages:
1: In min(x) : no non-missing arguments to min; returning Inf
2: In max(x) : no non-missing arguments to max; returning -Inf
3: In min(x) : no non-missing arguments to min; returning Inf
4: In max(x) : no non-missing arguments to max; returning -Inf

And don't understand how to fix it. Probably some small mistake, but I'm fairly new to using r. Tried to attach the script and data but for some reason, it is not possible to attach the script.

Thanks for the help!

Best regards 
Erik

**Comment by nicholascarey** [comment]
Hi Erik, 

Yes, we will need a little more information.... 

What function are you using? You can paste in the code directly here. Or send via email to nicholascarey - aaaaaaat - gmail

**Comment by nicholascarey** [comment]
Solving via email. 

For posterity - it was various plot errors in `pcrit` and `calc_pcrit` stemming from using a short sparse dataset. Could definitely do with being tested for next version.  Have a hunch saw these before with small datasets.
