### ISSUE TITLE
Summary output enhancements

### ISSUE THREAD

**Issue by nicholascarey** [januarharianto/respR#12]
* Change 'Average Rate' to 'Average Background Rate'. Helps distinguish it from a calc.rate output

* Clarify or change `b0` and `b1` in the summary. `b1` is the result of interest, so should be clearly named

**Comment by januarharianto** [comment]
`calc_rate.bg()` has had an overhaul, but the outputs should be fixed.

Now prints individual rate calculations, and then the average when `print()` is called.
