### ISSUE TITLE
S3 functions 

### ISSUE THREAD

**Issue by nicholascarey** [januarharianto/respR#134]
Take a run through all of them and make sure they look consistent, and have consistent functionality (pos, message, rate.rev inputs, etc...)

**Comment by nicholascarey** [comment]
And make sure these inputs can be passed via the ... in the main call

**Comment by januarharianto** [comment]
Might open another issue but I am currently auditing the `auto_rate()` code and realised that the S3 `plot.auto_rate()` does not currently work. Forgot what was done but a note was written that it is an old plotting function, but the new plotting function wasn't provided to replace it. Might be a mistake in one of my updates o_O

**Comment by nicholascarey** [comment]
Don't worry about it. I just did a massive rewrite of all the S3 fns....  Committing it later today, maybe. 
I have made some minor code changes to fix various things, so i guess just be careful when merging them or look at the diffs.

"old plotting function" is an old note. Has been there forever :)

**Comment by nicholascarey** [comment]
I think you had a newer version using ggplot at some point, but it took forever, so reverted back to this "old" one

**Comment by nicholascarey** [comment]
Done in a bunch of recent commits. All work the same, look the same, print nice, etc etc. 

plots all working and revised to look a bit nicer too.. 

Should be good to go. 

phew
