### ISSUE TITLE
Various error checks

### ISSUE THREAD

**Issue by nicholascarey** [januarharianto/respR#14]
`calc.bg.rate`, `calc.rate`, `auto.rate`

It will be very easy, especially when we allow manual entering of a `bg.rate`, to get the `±` sign wrong. It should basically always be a negative value, so should include an error check that it hasn't been entered as a positive value. If it has, show a warning. 

There are probably situations we are not familiar with where there could be a net positive input of O2, so we still need to allow it, but at least we should warn the user.

**Comment by januarharianto** [comment]
My shitty implementation of validations means that this is a bigger problem than it should be, lol 😢  
I'll have to learn better validation skills. Give me some time to work this out.

Right now, the internal function `verify_units()` is creating those error messages. The error is correct - it recognised "mg", but it did not recognise "L" as that is a volume unit, but it needs to be a time unit.

One way to fix this is to convert this stop error to a warning, and then in the main `convert_rate()` function I add the stop condition that output is not recognised. 

I'll do that first, but this (and input validation of the entire package in general) needs optimisation.

**Comment by januarharianto** [comment]
>Warning if S,t, or P have been entered and o2.unit is something other than percentage. These are not needed for other units (true, yes?), so if they have been entered, user probably means to input % data, or is misunderstanding the functions so should have this flagged up.

Temperature and pressure values are needed to convert between O2 pressure units (Torr, hPa, kPa, mmHg, inHg) and other units. 

I don't think a warning is necessary, if S, t and P are unused and the user changes them, they're going to be ignored anyway..?

**Comment by januarharianto** [comment]
This thread is hard to deal with. I'm closing it and creating separate issues out of this.
