### ISSUE TITLE
S3 functions - what is best practice?

### ISSUE THREAD

**Issue by nicholascarey** [januarharianto/respR#163]
Is there a way of having these not show up in function index, autocomplete, etc?  I think they have to be exported. In which case CRAN insists on a `/value` (`@return` in roxygen)  entry, which if you have that R-CMD check then insists on all the other stuff.... 

I don't think every package has every S3 do this. 

Try `@S3method` tag in roxygen? Does that do `@export`?

Also how to get `?print.auto_rate` to open main auto_rate help file?  Other packages have this behaviour.  
e.g. `?print.aov`

**Comment by januarharianto** [comment]
> Is there a way of having these not show up in function index, autocomplete, etc? I think they have to be exported. In which case CRAN insists on a /value (@return in roxygen) entry, which if you have that R-CMD check then insists on all the other stuff....

I think this can be solved with the `@keywords internal` roxygen parameter unless I am understanding this incorrectly. Anyway, this could be something to explore for the next minor version. 

I'm thinking of S4 methods or even R5 (just started looking into them) as a practice for the next version... which might solve this anyway.

**Comment by nicholascarey** [comment]
Doh. guess that's why all the other internal fns don't show up... 🤦‍♂️   
I must have removed it from all of them at some point.  

`@rdname` is the tag for redirecting help commands - i.e. put `@rdname calc_rate`  in `print.calc_rate` roxygen tags.

Both added in branch I'm working on now...   2.1 coming soon...

**Comment by nicholascarey** [comment]
Actually `@rdname` does weird things to the help files like mix all the arguments together.... Never mind
