### ISSUE TITLE
Clarification of Volume as input

### ISSUE THREAD

**Issue by nicholascarey** [januarharianto/respR#18]
We mention in several parts of the help files that this function converts `calc.rate` outputs to mass-, surface area-, and **volume-** specific rates. This is a bit confusing, because volume-specific would appear to refer to the volume of the specimen (which is actually functionality which could be useful). The `volume` argument of the function however refers to the volume of the respirometer, which it uses with concentration data to calculate total O2 present and therefore rate used. 

This needs clarification.

**Comment by januarharianto** [comment]
`calc.mo2` is now `convert_rate`. I think we made some fixes to make this obvious. Instead of "volume-specific" we now use the term "volumetric" and specify that it is to the chamber. 

I'll have another audit to make sure it's clear.
