### ISSUE TITLE
Subsetting option in pcrit function?

### ISSUE THREAD

**Issue by nicholascarey** [januarharianto/respR#21]
Often the initial stages of an experiment are not ideal - the specimen might have unnatural elevated rates, or there are data from before the specimen has been sealed in. The end often has an extended section of zero rate if animal has died. These sections would interfere with the PCrit analysis. 

Ideally, the user will remove these, but those sections can be difficult to judge from the raw o2/time data. So it might be useful to include subsetting. Alternatively have a simple `trim.start` and `trim.end` arguments, however subsetting as in the other functions would be more consistent. i.e. choose `from` and `to` by `time`/`o2`/`row`

**Comment by januarharianto** [comment]
Now that `inspect_data()` has a quick overview of the rolling regression, this should not be too much of an issue. 

There is an internal subset function (`subset_data()`) that I could make visible in the package list. What do you think?

It's already available, just hidden from the documentation. It's used for all subsetting in all functions.

Try:
`subset_data(sardine.rd, from = 2000, to = 4000, by = "time")`

**Comment by januarharianto** [comment]
Holy crap, now that I see this I feel like subsetting might be better off as a separate function...

**Comment by januarharianto** [comment]
`subset_data()` is no longer internal since ccd408d4a7854061130b7ecd4b2a9149d87f6fbf.
