### ISSUE TITLE
Use time or row for width

### ISSUE THREAD

**Issue by nicholascarey** [januarharianto/respR#22]
`width` should accept a time period or row width, as well as proportion to do the multiple regressions over. This means the function would require a separate `by` function, or other way of telling it what `width` is indicating. For now, users can easily work out these themselves in proportion terms, so this is low priority. 

Multiple regression over equal O2 decreases would be unusual, so is *not* necessary.

**Comment by januarharianto** [comment]
I've added this to a checklist, closing.

**Comment by nicholascarey** [comment]
Yeah. Very low priority. I'm not sure it's necessary on second thoughts.
