### ISSUE TITLE
`inspect` - new branch, various changes

### ISSUE THREAD

**Issue by nicholascarey** [januarharianto/respR#26]
* If time data is uneven, some sort of indication how uneven. Should be able to easily indicate difference between unimportant tiny trailing decimal differences and gaps of several minutes in high resolution data. 

* Some sort of graphical output would be good, but dealing with the scale might be tricky. 

* A simple output of the min/max intervals might be sufficient. e.g. the squid data recording at 30s intervals, min/max are ~28-32s, so data is fine to use.

**Comment by januarharianto** [comment]
Notes so we won't forget:

- I tried doing a graphical output, it's lousy for big data. So we probably won't do anything graphical.
- The suggestion of simply showing what intervals are detected (max and min) is a good one. I'll implement it at some point.

**Comment by nicholascarey** [comment]
Bump. 

Was going to add this quickly (message about min/max intervals) but discovered a few other issues (plot/print bugs mostly). 

So made a new feature branch and editing title to cover all changes here.

One actual functional change - i added a `width` input to modify the rolling rate plot. Most of the time 0.1 is fine, but sometimes i want a different value...

**Comment by nicholascarey** [comment]
Ok, did a big update. Should be fine to merge into `dev` unless there are any further comments/suggestions...? 

Changes

- `time = 1` and `oxygen = 2` the defaults rather than `NULL`
- if `oxygen = NULL` now inspects ALL columns
- added `width` input for rolling reg plot (default 0.1)
- updated roxygen docs. There was quite a lot out of date...
- Added message if multiple columns inspected that subsequent functions will only use first 2 by default
- Muliple rate inspection plot improved. Now all plot on same axes ranges, better colours and spacing.
- FIX: Rolling rate plot failed with even a single NA in time or oxygen data.

`print.inspect`
- minor edits to console print out (e.g. messages print relevant columns names rather than both x/y col names, better spacing)
- if uneven time, now prints min/max intervals found
- time error locations now printed out when multiple o2 columns inspected

**Comment by januarharianto** [comment]
Since I'm quite confident that you know what you're doing, go for it. It's fine since we're on dev branch.

**Comment by nicholascarey** [comment]
haha, ok. Not sure i do sometimes 🙃

Btw, i think I'm going to make a separate version of this for flowthrough data - `inspect.ft` . 
It should actually be fairly simple. Currently you can inspect ft data fine but when you load it into `calc_rate.ft` you have to specify the columns within the `$dataframe`, so it's fiddly and there's no real advantage doing it.
