### ISSUE TITLE
Primary output is the non-corrected rate when a background rate is applied.

### ISSUE THREAD

**Issue by nicholascarey** [januarharianto/respR#29]
Testing. Using `squid` to get a bg rate

`bg_rate <- calc.bg.rate(squid, plot=T)`

Gives a background correction of -0.000238

`calc.rate(sardine, from = 2000, to = 4000, by = "time")`
`calc.rate(sardine, from = 2000, to = 4000, by = "time", bg = bg_rate)`
`calc.rate(sardine, from = 2000, to = 4000, by = "time", bg = -0.000238)`

All result in `Rate (b1): -0.000705`

**Comment by januarharianto** [comment]
We've completely changed how background rate adjustments work, it is now a separate function. I'll close this.
