### ISSUE TITLE
Slight discrepancy in bg-corrected rate?

### ISSUE THREAD

**Issue by nicholascarey** [januarharianto/respR#31]
Probably a rounding error somewhere, but the corrected rate in `auto.rate` does not quite match the `b1-bg`

`bg_rate <- calc.bg.rate(squid, plot=T)`

Gives a bg rate of `-0.0002379409` or `-0.000238` rounded

`auto.rate(sardine, logic = "automatic", bg = bg_rate)`

Output - 
`--- Subset Information ---`
`b1-bg   rsq from.row to.row from.time to.time from.o2 to.o2 row.len time.len      rate.2pt`
`1 -0.0004239086 0.983     3690   6854      3689    6853    92.5  90.4    3165     3164 -0.0006637168`

However:
`0.0006637168-0.0002379409 = 0.0004257759`
and
`0.0006637168-0.000238 = 0.0004257168`

A discrepancy of `-0.0000018`

Not huge, but just wondering where it comes from...

**Comment by januarharianto** [comment]
We've completely changed how background rate adjustments work, it is now a separate function. I'll close this.
