### ISSUE TITLE
Ambiguous error message in convert_rate when `output.unit` is wrong

### ISSUE THREAD

**Issue by januarharianto** [januarharianto/respR#37]
This issue is extracted from #14 with some edits.

> convert_rate(0.004, o2.unit = "%", time.unit = "s", output.unit = "mg/L", volume = 12.3)
> 
> `Error: unit 'L' is not in the respR unit database.`
>
> Can we change this to specify output unit is malformed?

**Comment by nicholascarey** [comment]
Mostly dealt with in 1.1.0. 

``` 
Error: unit 'L' cannot be recognised. Check unit strings are in correct order O2/Time or O2/Time/Mass. 
```

Should be sufficient. Maybe in the future we do a proper 'not recognised as time, o2 or mass unit'.
