### ISSUE TITLE
calc_rate.ft output plot enhancements

### ISSUE THREAD

**Issue by januarharianto** [januarharianto/respR#40]
Add another plot to show the subset plot -- similar to `calc_rate()`. We then have a 2-column plot output.

At the same time, let's not plot anything if the input data is a single numerical value:
```r
calc_rate.ft(delta.o2 = 0.76362, flowrate = 0.00039)
```
Because that's not a very useful plot.

**Comment by nicholascarey** [comment]
All this covered in recent updates I haven't committed yet!
