### ISSUE TITLE
inspect() issues

### ISSUE THREAD

**Issue by nicholascarey** [januarharianto/respR#45]
Couple of things:

- The results table (pass/fail) is not shown on  2 column df, or if oxygen/time columns are specified with column index numbers

- What default width is being used for the rate plot? It seems a little too wide, compared to that in the old function (`inspect_data`). See attached plots

- Also, regarding the plots (and I'm pretty sure we discussed this before), rate plot should be same width as top plot. i.e. same x-axis. This is so you can more easily see the rate linked to a specific point in the experiment. Obviously this means it needs padded with blank values at start/end. Or just plot each rate against the middle of the width range used to get it, and make sure the bottom plot has same `xlim` as the top one... ?

[inspect_new.pdf](https://github.com/januarharianto/respR/files/1834057/inspect_new.pdf)
[inspect_old.pdf](https://github.com/januarharianto/respR/files/1834058/inspect_old.pdf)

**Comment by januarharianto** [comment]
1. Results are there, they are hidden if you save the function output as an object. In that case, just do a `print()`.

2. The width is 0.2 to be consistent with `auto_rate()`'s default width. It's all right, but I can work it back to 0.1, but don't think it changes the patterns much.

3. Ok, good idea. It's rolling to the right so I'll just need to pad blanks to the left of the plot. Will work on that for 0.1.

**Comment by januarharianto** [comment]
Also, the x axis **must** be index. If it's time-based, we'd need to do time-based rolling regression. That would be inefficient (and won't help much, I think the principal aim is to learn the "shape" of the data to deal with it)

**Comment by nicholascarey** [comment]
1. ok, but would be good to show by default. I find it reassuring. Also to be consistent with passing it a multi column df

2. Makes sense. It totally depends on the total data size and how quickly rates are changing how it looks. I think more rate resolution in this plot is better since you'll typically be looking over an entire experiment, which could be really long and have have several phases (like this e.g. i attached)

3. Oh yeah, i know. Index is fine for this fn. It's just for better visual aid.

**Comment by januarharianto** [comment]
Hmm was editing the code today, but because I offloaded the print to the S3 `print()` function I can't show it by default without getting duplicate table outputs.

I think a workaround would be to simply add a `print()` line inside the pipe:

```{r}
library(respR)
library(dplyr)

x <- sardine.rd %>%
  inspect() %>%
  print() %>%
  auto_rate()
```

**Comment by januarharianto** [comment]
This was fixed ages ago, cleaning house
