### ISSUE TITLE
convert_rate() output for auto_rate() objects (possibly others?)

### ISSUE THREAD

**Issue by nicholascarey** [januarharianto/respR#46]
We discussed this somewhere - not sure where. Adding it here so we don't forget. 

Print out in console for `convert_rate` on `auto_rate()` objects should only show top result. Currently it prints big block of inputs and outputs. User probably only interested in `input[1]` and `output[1]`. Can be confusing because next outputs can be *very* different in value, depending on the data structure. Should be more clear this is the min/max/most linear result, as in the original auto_rate output. 

Should probably be a clear primary, top-level result in the `convert_rate` output object too. 
Of course they should be able to extract all the others manually if they want to.

**Comment by januarharianto** [comment]
Sounds good, working on it.

**Comment by januarharianto** [comment]
Fixed some time ago, cleaning house.
