### ISSUE TITLE
Error during installation by user

### ISSUE THREAD

**Issue by januarharianto** [januarharianto/respR#52]
This is a follow up on an issue that was reported on ResearchGate.

> Hey Januar, I receive the following error msg when trying to install your package, maybe you/anybody has encountered this problem before?
> Greetings
> ~S
> * installing *source* package 'respR' ...
> ** R
> ** data
> *** moving datasets to lazyload DB
> Warnung: namespace 'respR' is not available and has been replaced by .GlobalEnv when processing object 'test_lin_data'
> Warnung: namespace 'respR' is not available and has been replaced by .GlobalEnv when processing object 'test_lin_data'
> ** tests
> ** preparing package for lazy loading
> Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : there is no package called 'rlang'
> ERROR: lazy loading failed for package 'respR'

On first look it seems like an error with the `test_lin_data.rda` file. I'm going to need additional information before I can troubleshoot this. No other users have reported this, so it could also be an issue that is specific to the user.

**Comment by muchaste** [comment]
rlang and stringi were missing, now installation works

**Comment by januarharianto** [comment]
Oh cool! Thanks for the update - I was worried about issues with OS compatibility for a moment there (tests on different machines were limited). Closing this.
