### ISSUE TITLE
Error in import_file() using .txt file from from Loligo Witrox

### ISSUE THREAD

**Issue by lbpotts** [januarharianto/respR#57]
I'm having an issue importing my raw Loligo Witrox txt file using the import_file() command. I've attached the code I'm running, with the error messages, along with the .txt file itself. Any assistance would be greatly appreciated! 

`import_file("LP12_22C_Fish1_Jun6_raw.txt")
Loligo Witrox Logger Detected

Error in setnames(rdt, c("datetime", "time", "pressure", "phase", "temp",  : 
  Can't assign 6 names to a 47 column data.table`

[L12_22C_Fish1_Jun6_raw.txt](https://github.com/januarharianto/respR/files/2983858/L12_22C_Fish1_Jun6_raw.txt)

**Comment by nicholascarey** [comment]
Hi. 

Yes, this is known problem with some Witrox files. Should be fixed in the next version. For now it's easy enough to import by other means. 


```
library(respR)
library(data.table)
library(lubridate)

## create function
parse_witrox <- function(path) {
  raw <- fread(path, skip = 37)
  
  ntime <- format_time(raw[,1],
                       format = "dmyHMSp")
  
  out <- data.table("Elapsed (s)" = ntime[,1], raw)
  return(out)
}


## set path
path <- "path/to/data"

## import - note it adds a new column as first column. 
## So all columns are shifted along by one
data <- parse_witrox(path)

## check
inspect(data, time = 1, oxygen = 8)
```

Let us know if you have any other issues. 

Nice clean looking data, by the way!

**Comment by lbpotts** [comment]
Thank you!
