### ISSUE TITLE
Error with `auto_rate()` related to package `data.table`

### ISSUE THREAD

**Issue by januarharianto** [januarharianto/respR#58]
Error code:

```
 Error in forder(x, -rank(density)) : 
  Attempting to order a 0-column data.table. 
```

Possible due  to 2 things: 

1. No suitable linear region is detected resulting in no data being passed on to `data.table`
2. Recent `data.table` update is messing with how things work

**Comment by nicholascarey** [comment]
Still an issue. Can recreate with these data

https://www.dropbox.com/s/0rw9b1vm6d4rzuu/ar_fail_data.csv?dl=1

```
ar_fail_data <- read.csv("ar_fail_data.csv")

auto_rate(ar_fail_data)
```

```
 Error in forder(x, -rank(density)) : 
  Attempting to order a 0-column data.table. 
```

Stops a loop dead. Would be better if it saved *something*, even if just filled everything with NAs

**Comment by januarharianto** [comment]
Ok found the bug, the kernel density detection method returns a `list()` with no values when the width specified is smaller than the length of any data segments identified. Happens when the dataset is small to begin with, but I don't have an exact figure to define "small" in this case.

I have to think of a way to address this. Don't want to modify existing functionality, so I might just catch the error and either

1. skip the segment; or
2. stop the analysis and ask the user to use a smaller width; or
3. tell the user that the data is too small and suggest manual methods (or re-adjust the window automatically while telling the user that the width has been adjusted)

**Comment by januarharianto** [comment]
This might take a few days to brainstorm, I will probably implement each of these and test them
