### ISSUE TITLE
`pcrit()` needs to show the slopes for the lines that produce the intersections

### ISSUE THREAD

**Issue by januarharianto** [januarharianto/respR#59]
This is a feature request. The slope values can be used for other metrics.

**Comment by januarharianto** [comment]
Temporarily addressed in  b245f254daf69c96ecebef25a2c32d2b443b756e. Coefficients for broken stick line are now added to `summary()`. 

It might be better to use a new function to pull the metrics from the results (and do other fancy analyses on the data), so I'll do that.

**Comment by nicholascarey** [comment]
Yes, i've been meaning to suggest exactly this for ages. A function to extract and filter results from objects, especially auto_rate, based on different criteria (e.g. R2, filter out +ve or -ve slopes, etc). Not sure if there should be one for each function, or one overall one that will handle everything. 

Some notes i made earlier - 

Quality control or selection function
- extract all results based on R2, percentile, filter out +ve values etc.
- auto_rate - need some quality control for min/max rates. Something based on R2 probably. Can output min/max rate over time period, but sometimes this is lowest but clearly crappy. 
- See NLA1_03 rep 5 for example
- for now - amend vignette to show how highest r2 can be extracted?

**Comment by januarharianto** [comment]
Closed for now. New functionality is planned.
