### ISSUE TITLE
pcrit() and calc_pcrit() fails to plot

### ISSUE THREAD

**Issue by nicholascarey** [januarharianto/respR#60]
`pcrit()` and `calc_pcrit()` fails to plot with some data, and stops analysis. Result is returned if `plot = F` though

```
## fails
pcrit(urchins.rd, plot = T)
calc_pcrit(urchins.rd, time = 1, oxygen = 2, plot = T)
```
```
 Error in plot.default(...) : 
  formal argument "xlab" matched by multiple actual arguments 
```
```
## works
pcrit(urchins.rd, plot = F)
calc_pcrit(urchins.rd, time = 1, oxygen = 2, plot = F)
```

My guess is something to do with shorter datasets

**Comment by nicholascarey** [comment]
HOWEVER

It works if the same data are in an `inspect` object

```
urch_insp <- inspect(urchins.rd, time=1, oxygen = 2)
# works
pcrit(urch_insp, plot = T)
calc_pcrit(urch_insp, plot = T)
```

**Comment by januarharianto** [comment]
Whoa. Actually, I didn't add code to handle multi-column datasets properly so this is an unintended "feature". Will add.
