### ISSUE TITLE
Weird behaviour with running tests

### ISSUE THREAD

**Issue by nicholascarey** [januarharianto/respR#65]
Not sure what to classify this as, or if it's a problem at all, though I'm guessing it will be with CRAN automated tests. 

See test-auto_rate file, around L62. I had to put this delete pdf command in, because running the tests makes it save that file to the tests directory. BUT -  only when i run it via cmd-shift-T, never if i just run it by selecting and running the actual code. Not a huge problem, but just weird, and may cause problems with CRAN checks. 

In fact, i found it simpler to just put skip_on_cran() at the top of every test file for loomeR. They're only for our benefit, so as long as we run them they don't need to!

**Comment by januarharianto** [comment]
Yeah, skip if necessary.
