### ISSUE TITLE
auto_rate - method = "default"

### ISSUE THREAD

**Issue by nicholascarey** [januarharianto/respR#66]
Doesn't seem to be a reason to have this method? Can only see it applied in plot and print functions. Probably could be removed from code?

**Comment by nicholascarey** [comment]
In fact, it seems to give an error if you try to use it

**Comment by nicholascarey** [comment]
And stops me from getting 100% test coverage!  😂

**Comment by januarharianto** [comment]
Oops. This was from the previous version of `auto_rate ()` where `method = 'linear'` replaced `method = 'default'` but I obviously did not clean up the code enough. I'll just point both 'linear' and 'default' to the unsupervised learning method. For backward compatibility.
