### ISSUE TITLE
import for non-US raw data formats

### ISSUE THREAD

**Issue by muchaste** [januarharianto/respR#68]
I use respR with data from the pyro oxygen logger from a german PC. The logger uses commas instead of dots as decimal separator. The date is printed as e.g. 31.01.2019 (January 31st 2019).
To make the files readable via the `import_file `function, I manually replaced all commas with dots. However, the date is not recognized. I haven't found out how to access the subfunctions of `import_file` to change the date format and separators. I imagine this shouldn't be too much work. Can you help me with this, i.e. integrate support for this european format or help me to access the `parse_pyro` subfunction?
Thank you and btw amazing work on this package! <3

*edit: I attached a sample file with German format
[example_log.txt](https://github.com/januarharianto/respR/files/3605236/example_log.txt)

**Comment by nicholascarey** [comment]
Hi. Thanks for the file and bug report! 

Yes, this is a known issue - someone else using European comma formats has been in touch about it. We are thinking of how to support it. It is difficult to detect automatically. It's a problem for your oxygen data, but for the date/times you don't actually need `respR` to recognise them - your data has a numeric time column already! 

In the meantime see below. As long as your basic file structure doesn't change this should work with them all. The important part is the `dec = ","` in `fread` which tells it the separator is a comma. 

```
## Create function
import_pyro_euro <- function(path){
  
  ## read raw data
  raw_data <- data.table::fread(path, fill = TRUE, skip = 13, dec = ",")

  ## convert to data frame (because of bug in format_time with data.tables)
  ## and remove two redundant columns
  raw_data <- data.frame(raw_data[,1:29])
  
  ## rename columns
  ## You can modify these to whatever you want, or delete this part entirely
  names(raw_data) <- c("Date", "Time", "Time_s", "Comment", 
                       "CH_1_OX", "CH_2_OX", "CH_3_OX", "CH_4_OX", 
                       "CH_1_T", "CH_2_T", "CH_3_T", "CH_4_T", 
                       "Pressure_mbar", "Humidity_percent", "Temp_Probe_C", "Int_Temp_C",
                       "Analog_In_mv", 
                       "CH_1_dphi", "CH_2_dphi", "CH_3_dphi", "CH_4_dphi", 
                       "CH_1_sig_int_mV", "CH_2_sig_int_mV", "CH_3_sig_int_mV", "CH_4_sig_int_mV", 
                       "CH_1_amb_light_mV", "CH_2_amb_light_mV", "CH_3_amb_light_mV", "CH_4_amb_light_mV")
  
  ## return
  return(raw_data)
}


## Use function to import a file

## set path to file
path <- "~/Downloads/example_log.txt"

## import
exp_01 <- import_pyro_euro(path)


## Your data already has numeric time in column 3, which you can use in respR
inspect(exp_01, time = 3, oxygen = 5)

## If it didn't have the time column or it is malformed for whatever reason, you can convert the 
## date/time columns in format_time. 
## It adds the new numeric time column at the end, but starts at 1 instead of zero. 
exp_01 <- respR::format_time(exp_01, time = c(1:2), format = "dmyHMS")


## If you did import date/times with commas, or any other separator, format_time can handle 
## these fine!

dates <- data.frame(Date = c("10,08,2019", "10,08,2019", "10,08,2019", "10,08,2019"),
                    Time = c("15,44,46", "15,44,47", "15,44,48", "15,44,49"))

format_time(dates, time = 1:2, format = "dmyHMS")
```

**Comment by muchaste** [comment]
Thank you so much for the quick support! Works like a charm. 
I've encountered these parsing problems a couple of times and also had an exchange with Matthew Birk from the respirometry package about this.
You guys can probably do this much better than me but how about a routine that imports only the first line of raw data with basic settings and checks whether the values are numeric or characters. If numeric columns (temperature, oxygen,...) return as characters, change the separator, re-import and re-try. 
Or pass it as an argument for the import_file() function on to the fread function under the hood so that the user can easily input the separator and if necessary date format.
Best wishes!

**Comment by nicholascarey** [comment]
No problem. Cooincidentally someone else has just contacted me with the exact same problem, so i passed them the same function. We'll make sure it's supported in the next release. Those are good suggestions, thanks!

**Comment by nicholascarey** [comment]
Reopening this because it's come up again with a user recently. Will have a stab at fixing it. 

Easy way - add a `dec` input to the function to pass to `fread`. 

Hard way - auto detect this. Should be fairly simple? Read in some lines, use regex to look for `.` or `,`? The `reader::get.delim` function may be useful, at least in *removing* the delimiter then looking for the `dec`. Also maybe someone has already done this....

**Comment by nicholascarey** [comment]
[pyro11_euro.txt](https://github.com/januarharianto/respR/files/4272024/pyro11_euro.txt)
[2019_05_12 expmetal_SMR.txt](https://github.com/januarharianto/respR/files/4272029/2019_05_12.expmetal_SMR.txt)

Two files for testing

**Comment by nicholascarey** [comment]
Added in 1d850f88f3b7c2d84deb0745a7074d9fb829efd6

Suggestion from @muchaste was a good one. Added internal `get_dec` fn to read in some lines and see which `dec` outputs numeric columns. 

Spectacularly broke firesting/pyro importing, so had to rewrite parser completely.
