### ISSUE TITLE
calc_pcrit - name conflict with `respirometry` package

### ISSUE THREAD

**Issue by nicholascarey** [januarharianto/respR#84]
Adding here so we don't forget to discuss it. 

`respirometry` also has a function `calc_pcrit` released about a month before ours. 

Should we have a *third* version to avoid any conflicts?

**Comment by januarharianto** [comment]
Hmm yes. It's also about time... to investigate the new pcrit methods

**Comment by januarharianto** [comment]
Anyway let's think of a new function name and I'll take a stab at implementing nonliner pcrit fitting. Hopefully not too tough to automate.

**Comment by nicholascarey** [comment]
Actually, a new name would be more correct. I just remembered a reviewer complaining about us using the term 'pcrit' with oxygen concentration units, because it technically means critical *pressure* of O2, and i've since seen a couple of review papers use some variation on 'O2crit' to cover both. So:
`o2crit`
`calc_o2crit`
`oxycrit`

... or some other variation.

**Comment by nicholascarey** [comment]
Also this paper should be useful. 4 methods compared, including 2 non-linear

[jeb210633.full.pdf](https://github.com/januarharianto/respR/files/4902245/jeb210633.full.pdf)

**Comment by januarharianto** [comment]
Thanks. Starting work on this, will check non-linear technique(s) first and foremost since it was something that I remember we said we would work on after those reviews on our publication.

**Comment by nicholascarey** [comment]
Cool. Yep, this was the main one that prompted that

[marshall 2013.pdf](https://github.com/januarharianto/respR/files/4902891/marshall.2013.pdf)

**Comment by nicholascarey** [comment]
Also this thread 

https://github.com/januarharianto/respR/issues/9

Can you merge issues?

**Comment by nicholascarey** [comment]
There was a recent back-and-forth on pcrit too 
[jeb163717.full.pdf](https://github.com/januarharianto/respR/files/4902902/jeb163717.full.pdf)
[jeb200253.full.pdf](https://github.com/januarharianto/respR/files/4902903/jeb200253.full.pdf)
[jeb203646.full.pdf](https://github.com/januarharianto/respR/files/4902904/jeb203646.full.pdf)

**Comment by nicholascarey** [comment]
And i have  bunch of other random papers in my "pcrit methods" folder! I will try and go through them at some point and make a list of possible other methods. 

[Mangum, Van Winkle - 1973 - Responses of aquatic invertebrates to declining oxygen conditions.pdf](https://github.com/januarharianto/respR/files/4902919/Mangum.Van.Winkle.-.1973.-.Responses.of.aquatic.invertebrates.to.declining.oxygen.conditions.pdf)
[portner et al 1985.pdf](https://github.com/januarharianto/respR/files/4902920/portner.et.al.1985.pdf)
[Richards 2011.pdf](https://github.com/januarharianto/respR/files/4902921/Richards.2011.pdf)
[Rogers et al 2016.pdf](https://github.com/januarharianto/respR/files/4902923/Rogers.et.al.2016.pdf)
[Kapper Stickle 1987.pdf](https://github.com/januarharianto/respR/files/4902918/Kapper.Stickle.1987.pdf)
[10.1242@jeb.210492.pdf](https://github.com/januarharianto/respR/files/4902910/10.1242%40jeb.210492.pdf)
[leiva urbina 2015.pdf](https://github.com/januarharianto/respR/files/4902911/leiva.urbina.2015.pdf)
[monteiro kalinin 2013.pdf](https://github.com/januarharianto/respR/files/4902912/monteiro.kalinin.2013.pdf)
[Nickerson 1989.pdf](https://github.com/januarharianto/respR/files/4902913/Nickerson.1989.pdf)
[stinchcombe kirkpatrick 2012.pdf](https://github.com/januarharianto/respR/files/4902914/stinchcombe.kirkpatrick.2012.pdf)
[1-s2.0-0022098175900258-main.pdf](https://github.com/januarharianto/respR/files/4902917/1-s2.0-0022098175900258-main.pdf)

**Comment by januarharianto** [comment]
I wonder if we can use unsupervised learning or discriminant analysis to predict the critical point. All of these techniques seem to require a lot of manual user input i.e. equation to use, the dV/dP threshold

**Comment by nicholascarey** [comment]
o_O   Sounds like a whole new methods paper...

**Comment by januarharianto** [comment]
Ok the plan.

1. Implement the manual non linear techniques first.
2. Develop a pattern matching technique...
3. Compare.

Who knows.

**Comment by nicholascarey** [comment]
just a note:

`pcrit()` is broken for me when `parallel = T`.  Getting this error message (after it tries for a VERY long time - couple of mins at least). 

```
calc_pcrit(inspect(squid.rd))
```
```
Performing broken-stick analysis (Yeager and Ultsch 1989)...

 Error in makePSOCKcluster(names = spec, ...) : 
  Cluster setup failed. 11 of 11 workers failed to connect. 
```

No idea when this might have started. I updated to R 4.0.2 and RStudio 1.3.959 fairly recently. Checked on two computers, but both on latest versions of everything...

**Comment by nicholascarey** [comment]
Renamed `oxy_crit`. Parallel issue went away. Also made `parallel = FALSE` the default

Closing and moving the useful refs etc to other issue.

f3123cfaf0be07225ab6c16e125e5bbd95f88493
