### ISSUE TITLE
respR won't load

### ISSUE THREAD

**Issue by kera171** [januarharianto/respR#89]
Good day,

I've been trying to load respR and I keep getting the following error message:

Error: Failed to install 'respR' from GitHub:
  (converted from warning) cannot remove prior installation of package ‘glue’

How do I fix this?

Thank you.

**Comment by nicholascarey** [comment]
Hi. I’m not at my computer, so can’t really look into it right now. But this is a general R error, probably not anything to do with our package in particular. You could try some of the suggestions

 https://stackoverflow.com/questions/45922418/error-in-install-packages-cannot-remove-prior-installation-of-package-dbi

**Comment by kera171** [comment]
Got it. I will try them. Thank you

**Comment by nicholascarey** [comment]
Ok. Let us know if you fix it (and how)!

**Comment by kera171** [comment]
I got it to work. I did detach("package:DBI", unload=TRUE), then restarted R, then did an update on packages and ran install.packages("devtools")
devtools::install_github("januarharianto/respR") again. Thanks for the help! :)

**Comment by nicholascarey** [comment]
Ok, glad to hear that! I think restarting R was probably the key step. 
Let us know if you have any issues with the package. Just a note - if you are looking at the vignettes/guides, some of them are a little out of date. We are working on an update, so they should be updated soon. Any problems, let me know!
