### ISSUE TITLE
Identify Linear Subsets in Intermittent Respirometry

### ISSUE THREAD

**Issue by kestermcullough** [januarharianto/respR#90]
This package is excellent! Is work still being done on support for intermittent respirometry still to identify and subset replicates?

Some methods I have tried:
* RSQ filtering
* Calculate second derivatives from data, finding lowest second derivative that is not zero (zero can indicate linear slope, but also repeated outputs)
* Ramer–Douglas–Peucker algorithm (have not tried to implement yet) and filtering results for maximum negative slopes over a given period length

**Comment by januarharianto** [comment]
Hi mate

I’ve paused development for a bit due to the extra workload of online teaching, but now that exam marking is over, I’ll probably spend the next month or so tackling this :D 

I think Nick has come up with an algorithm, but yes - a rolling second derivative technique is actually a great idea and we’ll do more tests on this.

**Comment by kestermcullough** [comment]
That is great to hear! I am developing some respirometry techniques for wastewater and this will be a huge help.

Sorry I cannot be of more help with programming, but thank you both for making this software, and distributing it openly and continuing to maintain it.

**Comment by nicholascarey** [comment]
Hi Kester

Great to hear you have been finding the package useful! Yes, good suggestions thanks. It's something we have been meaning to work on for ages. It hasn't been a major priority for a few reasons:
- most intermittent-flow respirometry is done at very regular intervals, so it's pretty easy to loop through a big dataset to subset each replicate out using `subset_data`
- for non-regular intermittent-flow data, most people keep detailed notes about when the flushes occurred, so these can be used to subset as above
- I think no matter how we implement automatic detection of replicates it will be fallible, so will require some sort of confirmation step, and doing this in a nice user-friendly way will be a challenge

As Januar mentioned, I did create a function `subset_rate` which may help. It allows you to subset `auto_rate` results by all sorts of metrics including RSQ, and also sign of the rate, data regions, percentiles etc. So for example, if you ran `auto_rate` on a big intermittent-flow dataset you could then exclude positive rates so you know it hasn't included linear regions in flush periods, and set a minimum duration and exclude overlapping rates so each *should* come from a unique replicate. It works really well so far, but i haven't tested it on this particular case. It's in the `feature/filter_rate` branch if you want to have a look and should be in the next version. It's more-or-less finished, but I want to add one more criteria and need to discuss with Januar about some of the terminology we use :)

Let us know how it goes with your analyses and any other bugs/issues/improvements/feature ideas you might have! And of course any outputs (papers, reports etc). I'm also working on a new website where we will have a page of these. 

Cheers, Nick
